rm -f ./dsp_output/monopolar/*
rm -f ./dsp_output/bipolar/*
rm -f ./executable/*
rm -f ./ez_pac_output/*
rm -f ./ez_top/input/*
rm -f ./ez_top/output/*
rm -f ./nbm1/*
rm -f ./nbm2/*
rm -f ./research_matfiles/*
rm -f ./trc/temp/monopolar/*
rm -f ./trc/temp/bipolar/*
rm -f ./trc/output/*
rm -f ./temp_pythonToMatlab_dsp/*
rm -f ./temp_pythonToMatlab_dsp_MATLAB/*

rm -f ./cudaica*.wts
rm -f ./cudaica*.sph
rm -f ./cudaica*.sc
rm -f ./cudaica*.fdt
